- name: install nginx
  apt:
    name: nginx
    state: present
- name: copy config
  template:
    src: wp.conf
    dest: /etc/nginx/sites-enabled/
- name: start nginx
  service:
    name: nginx
    state: started
